sudo: required
services:
  - docker

before_install:
  -  docker build -t rohitss912/frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rohitss912/frontend-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend-react"
  env: "FrontendReact-dev"
  bucket_name: "elasticbeanstalk-ap-south-1-098636972055"
  bucket_path: "frontend-react"
  on:
    branch: master
  access_key_id: 
    secure: "$ACCESS_KEY"
  secret_access_key: 
    secure: "$SECRET_KEY"