sudo: required
services:
  - docker

before_install:
  -  docker build -t rohitss912/frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rohitss912/frontend-react npm run test -- --coverage